server:
  port: 8085

spring:
  application:
    name: auth-service

grpc:
  client:
    benutzer-service:
      address: 'discovery:///benutzer-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    konto-service:
      address: 'discovery:///konto-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
