spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: http://localhost:8085/
          predicates:
            - Path=/api/auth/**

        - id: benutzer-service
          uri: http://localhost:8084/
          predicates:
            - Path=/api/benutzer/**

        - id: finanz-service-einnahmen
          uri: http://localhost:8086/
          predicates:
            - Path=/api/einnahmen/**

        - id: finanz-service-ausgaben
          uri: http://localhost:8086/
          predicates:
            - Path=/api/ausgaben/**

        - id: finanz-service-budget
          uri: http://localhost:8086/
          predicates:
            - Path=/api/budget/**

        - id: finanz-service-ziel
          uri: http://localhost:8086/
          predicates:
            - Path=/api/ziel/**

        - id: konto-service
          uri: http://localhost:8087/
          predicates:
            - Path=/api/konto/**

        - id: transaktionen-service
          uri: http://localhost:8088/
          predicates:
            - Path=/api/transaktionen/**
  discovery:
    enabled: true

application:
  name: gateway-service

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

