spring:
  application:
    name: finanzdaten-service
  datasource:
    url: jdbc:mysql://localhost:3306/finanzdaten_service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Ba@2024
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariPool


# Kommentierte MySQL Datenbank Konfiguration für H2 Konfiguration
# spring:
#   datasource:
#     url: jdbc:h2:mem:testdb                              # H2 Datenbank URL
#     driver-class-name: org.h2.Driver                      # H2 Treiber
#     username: sa                                          # H2 Standard Benutzername
#     password: password                                    # H2 Standard Passwort
#     hikari:
#       maximum-pool-size: 100                              # HikariCP Konfiguration
#       minimum-idle: 10                                    # HikariCP Konfiguration
#       idle-timeout: 30000                                 # HikariCP Konfiguration
#       max-lifetime: 1800000                               # HikariCP Konfiguration
#       connection-timeout: 30000                           # HikariCP Konfiguration
#       pool-name: HikariPool                               # HikariCP Konfiguration
#   jpa:
#     hibernate:
#       ddl-auto: update                                    # JPA Konfiguration
#     show-sql: true                                        # JPA Konfiguration
#     properties:
#       hibernate.dialect: org.hibernate.dialect.H2Dialect  # H2 Dialekt

server:
  port: 8086

grpc:
  server:
    port: 9096
  client:
    konto-service:
      address: 'discovery:///konto-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    benutzer-service:
      address: 'discovery:///benutzer-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
