spring:
  application:
    name: benutzer-service

server:
  port: 8084

grpc:
  server:
    port: 9099

spring.datasource:
  url: jdbc:h2:mem:bndb
  driver-class-name: org.h2.Driver
  username: sa
  password:

spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect

spring.h2.console.enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
